import Head from "next/head";
import Image from "next/image";
import { HeroSection,Sidebar,AboutSection,FollowSection } from "../components";
import  {useState} from "react"
export default function Home() {
  const [sideBarOpen, setsideBarOpen] = useState(false)
  const openSideBar = () =>{
    setsideBarOpen(!sideBarOpen);
  }
  return (
    <div className=" min-h-screen flex flex-col overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={true} />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600&family=Oswald:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <HeroSection openSideBar={openSideBar} />
      <Sidebar openSideBar={openSideBar} sideBarOpen={sideBarOpen} />
      <AboutSection />
      <FollowSection />
    </div>
  );
}
